site_name: Stroke Prediction Dashboard
site_description: Documentation du projet de prédiction d'AVC avec FastAPI et Streamlit
site_author: Chaima
repo_url: https://github.com/Saleh-chanselme/stroke-api/tree/chaima  
repo_name: GitHub


nav:
  - Accueil: accueil.md
  - API Client: api_client.md
  - APP: app.md

plugins:
  - mkdocstrings